
get http://localhost:4000/author-api/authors

###
post http://localhost:4000/author-api/register
Content-Type: application/json

{
    "role":"author",
    "username":"Buvan",
    "password":"Buvan@123",
    "email":"Buv@gmail.com"
}

###
put http://localhost:4000/author-api/update/Vikas
Content-Type: application/json

{
    "role":"author",
    "username": "Jai123",
    "password": "Jaiiiiiiiiii@12",
    "email":"vik@gmail.com"
}