####################################    AUTHOR   ##################################################
###get for author
get http://localhost:4000/author-api/authors

###post for author resgister
post http://localhost:4000/author-api/register
Content-Type: application/json

{
    "role":"author",
    "username":"Jai12",
    "password":"Buvan@12",
    "email":"Buv1@gmail.com"
}
### post for author login
post http://localhost:4000/author-api/login
Content-Type: application/json

{
    "role":"author",
    "username":"Jai12",
    "password":"Buvan@12"
}
### post for article
post http://localhost:4000/author-api/article
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
    "title":"JavaScript Basic",
    "category":"Programming",
    "content":"asdfgfghjkljhgfuygfvbnl;iuygnoiytsxcv;iuy sdfgkloiuygfdghjkl",
    "dateofCreation": "{{$datetime iso8601}}",
    "dateofModification": "{{$datetime iso8601}}",
    "username":"Jai",
    "comments":[],
    "status":true
}
###read the articles
get http://localhost:4000/author-api/article/Jai

###delete an article by author
put http://localhost:4000/author-api/article/Jai/1711000257
Content-Type: application/json

{
    "status":true
}

### edit article by author
put http://localhost:4000/author-api/article
Content-Type: application/json

{
    "articleId":"1711000257",
    "title":"JavaScript Basic Part-1",
    "category":"Scripting",
    "content":"We will we will rock you",
    "dateofCreation": "2024-03-21T05:50:57.622Z",
    "dateofModification": "{{$datetime iso8601}}",
    "username":"Jai",
    "comments":[],
    "status":true
}







####################################    USER   ##################################################
### get for user
get http://localhost:4000/user-api/users

### post for user

post http://localhost:4000/user-api/register
Content-Type: application/json

{
    "role":"author",
    "username":"Jai12",
    "password":"Buvan@13222",
    "email":"Buv222@gmail.com"
}

### login for user
post http://localhost:4000/user-api/login
Content-Type: application/json

{
    "role":"author",
    "username": "Jai12",
    "password": "Buvan@13222"
}


###read all articles

get http://localhost:4000/user-api/article